export const fixtureScenarios = [
  "artifact-backed-assistant",
  "artifact-page-race",
  "artifact-history",
  "cancellation",
  "clipboard-timeout",
  "clipboard-success",
  "copy-large-assistant",
  "copy-older-assistant",
  "deadline",
  "draft-admission-cancellation",
  "history",
  "input-resource-copying",
  "mcp-close-unconfirmed",
  "mutation",
  "mutation-long-preview",
  "mutation-after-release",
  "mutation-after-release-with-continuation-barrier",
  "mutation-delayed-preview",
  "plan-review",
  "plan-review-recovery",
  "provider-no-usage",
  "provider-usage",
  "read",
  "reasoning-artifact",
  "reasoning-artifact-race",
  "reasoning-artifact-reorder",
  "reasoning-artifact-session-race",
  "reasoning-large-multiple",
  "reasoning-large-live",
  "reasoning-cancellation",
  "reasoning-failure",
  "reasoning-streaming",
  "reasoning-live-viewport",
  "reasoning-viewport",
  "reasoning-multiple",
  "review-completed",
  "review-operation",
  "review-operation-long-provenance",
  "review-recovery",
  "review-unavailable",
  "search",
  "resume",
  "session-selection-history",
  "shell",
  "skill-selection",
  "streaming",
  "target-navigation",
  "target-navigation-unavailable",
  "target-connection-multiple",
  "target-connection-pending",
  "target-picker-hostile",
  "target-unavailable",
  "todo",
  "tool-artifact",
  "tool-multiple",
  "unsafe-history",
  "unsafe-output",
  "web-search",
  "web-search-configuration-pending",
  "write",
] as const;

export type FixtureScenario = (typeof fixtureScenarios)[number];

export function isFixtureScenario(value: string): value is FixtureScenario {
  return (fixtureScenarios as readonly string[]).includes(value);
}
